### ISSUE TITLE
Monster hit dice dont include the additional hps

### ISSUE THREAD

**Issue by Dembig94** [Shwaffle/Encounter-Sheet-Imports#1]
First off I love the encounter sheet but if you want to roll the hps for individual monsters the stat block does not show the additional hps to add. for example an Ogre Zombie is 9d10 +36 but your stat block doesn't show the +36 so you have to look up every monster in the book to ensure HPs are generated correctly

**Comment by MattBerg11** [comment]
Wow, apparently I don't get notifications for issues on Github! I'll have to look into that. I received an email about this as well, so I will echo my reasoning for that below.

> As for hit dice/HP, this section is working as I intend it to. The +- after the 2d6 is the Constitution Modifier which is added after each dice roll to get your final HP. (So for a Kobold it would be -2 due to the ConMod being -1 and it's HD being 2d6). The reason I do not display the modifier amount, is because a DM is either going to reroll all the HP themselves and include the ConMod with it, or they are going to use the displayed average HP. For the Ancient Black Dragon, the Average HP is calculated like:
> 
> HP: 367
> Hit Dice: 21d20
> ConMod: +7
> 
> 21*(10.5+7) Rounded down
> 
> The 10.5 is the 'Average' for a 20 sided die. (6 sided is 3.5, 12 is 6.5 etc)
> 
> You can use the formula (HitDice * ((DiceSize / 2) + .5) + ConMod) to figure out the Average HP of any monster in D&D 5e. There might be an exception here or there, but this is the standard for at least 99% of the monsters.
> 
> So as we can see with that, the full inclusion of the totalled ConMod at the end of the hit dice is not required to be displayed. Let me know if you need help with anything else!


Edit: Due to the ConMod being added to dice rolls is a standard in D&D, I assume that all DMs do know that they must do that, if they roll the HP vs using the average.
